In [1]:
from rdkit import Chem
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, ShuffleSplit, GridSearchCV, cross_val_score, cross_validate
import os
import glob
from scipy.stats import norm
import math
import random

In [2]:
from sklearn.neural_network import MLPRegressor
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, cross_val_score
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error 


T_0 = pd.read_excel('2053-y.xlsx')
T=np.array(T_0)
#from sklearn import preprocessing  
#min_max_scaler = preprocessing.MinMaxScaler() 
#T=T_minMax = min_max_scaler.fit_transform(T)
#T=T.ravel()

print(T)  
print(len(T))

[[1]
 [1]
 [0]
 ...
 [0]
 [0]
 [0]]
2053


In [3]:
#读入特征    1000种描述符数据 
X=pd.read_excel('CDK + CDK extended + Substructure + Substructure count.xlsx')
X=np.array(X) 
#min_max_scaler = preprocessing.MinMaxScaler() 
#X=X_minMax = min_max_scaler.fit_transform(X)
print(X)
print(len(X[0]))
print(len(X))

[[ 0  0  0 ...  0  0  7]
 [ 0  0  0 ...  0  0  3]
 [ 0  0  0 ...  0  0 30]
 ...
 [ 0  0  0 ...  0  0  7]
 [ 0  0  0 ...  0  0  7]
 [ 0  0  0 ...  0  0  7]]
2662
2053


In [4]:

# FAK 1 -8

In [5]:
from sklearn.model_selection import train_test_split
X_train,  X_test,  T_train,  T_test  =  train_test_split(X,T,test_size=0.100,random_state=90)

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,f1_score
import lightgbm as lgbm

clf=lgbm.LGBMClassifier(boosting_type='gbdt',colsample_bytree=1.0,feature_fraction=0.8,bagging_fraction=0.8,num_leaves=20,min_child_samples=50,max_depth=-1,
                        learning_rate=0.05,n_estimators=200, n_jobs=-1)
clf.fit(X_train,T_train)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb
plt.style.use('ggplot')
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

regressor = lgb.LGBMRegressor(n_estimators=400, n_jobs=-1)
regressor.fit(X_train,T_train)
lgb.LGBMRegressor(boosting_type='gbdt', class_weight=0.5, colsample_bytree=1.0,
       importance_type='split', learning_rate=0.05, max_depth=4,
       min_child_samples=50, min_child_weight=0.001, min_split_gain=0.0,
       n_estimators=200, n_jobs=-1, num_leaves=20,random_state=90, reg_alpha=0.01, reg_lambda=0.1, silent=True,
       subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
import pandas as pd
import numpy as np
import time
import logging
import os, sys
import psutil
import lightgbm as lgb
from datetime import datetime

from itertools import cycle
from sklearn import svm
from sklearn.metrics import *

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
#from sklearn.externals import joblib
from scipy import interp

T_pred = clf.predict(X_test)
confusion_matrix(T_test, T_pred)

In [ ]:
print (classification_report(T_test, T_pred , digits=4))

In [ ]:
f1=f1_score(T_test,T_pred,average='micro')
print("the f1 score: %.3f"%f1)

In [ ]:
from lightgbm import plot_importance
# 显示重要特征
fig = plt.figure(figsize=(10,10))
plot_importance(clf,max_num_features=10)
plt.show()


In [ ]:
T_pred = clf.predict(X_train)
confusion_matrix(T_train, T_pred)

In [ ]:
print (classification_report(T_train, T_pred , digits=4))

In [14]:
# 十倍交叉验证

In [15]:

from sklearn.model_selection import cross_validate

clf = lgbm.LGBMClassifier(boosting_type='gbdt', colsample_bytree=1.0, feature_fraction=0.8, bagging_fraction=0.8, num_leaves=20, 
                          min_child_samples=50, max_depth=-1, learning_rate=0.05, n_estimators=200)
cv = 10  # 十倍交叉验证的折数
scoring = ['accuracy', 'precision_macro', 'f1_macro']  # 评估指标


In [16]:
scores = cross_validate(clf, X_train, T_train, cv=cv, scoring=scoring, return_train_score=True)

mean_accuracy = scores['test_accuracy'].mean()
mean_precision = scores['test_precision_macro'].mean()
mean_f1 = scores['test_f1_macro'].mean()

std_accuracy = scores['test_accuracy'].std()
std_precision = scores['test_precision_macro'].std()
std_f1 = scores['test_f1_macro'].std()

mean_train_accuracy = scores['train_accuracy'].mean()
mean_train_precision = scores['train_precision_macro'].mean()
mean_train_f1 = scores['train_f1_macro'].mean()

std_train_accuracy = scores['train_accuracy'].std()
std_train_precision = scores['train_precision_macro'].std()
std_train_f1 = scores['train_f1_macro'].std()

print(f'Mean Accuracy (Test): {mean_accuracy:.4f} ± {std_accuracy:.4f}')
print(f'Mean Precision (Test): {mean_precision:.4f} ± {std_precision:.4f}')
print(f'Mean F1 Score (Test): {mean_f1:.4f} ± {std_f1:.4f}')

print(f'Mean Accuracy (Train): {mean_train_accuracy:.4f} ± {std_train_accuracy:.4f}')
print(f'Mean Precision (Train): {mean_train_precision:.4f} ± {std_train_precision:.4f}')
print(f'Mean F1 Score (Train): {mean_train_f1:.4f} ± {std_train_f1:.4f}')


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Pleas

[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LightGBM] [Warning] bagging_fraction is set=0.8, subsample=1.0 will be ignored. Current value: bagging_fraction=0.8
[LightGBM] [Warning] feature_fraction is set=0.8, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.8
Mean Accuracy (Test): 0.8673 ± 0.0287
Mean Precision (Test): 0.8679 ± 0.0290
Mean F1 Score (Test): 0.8671 ± 0.0288
Mean Accuracy (Train): 0.9814 ± 0.0018
Mean Precision (Train): 0.9817 ± 0.0018
Mean F1 Score (Train): 0.9813 ± 0.0018


In [15]:
#读入特征    描述符数据 
Z=pd.read_excel('CDK + CDK extended + Substructure + Substructure count（2015-2024）.xlsx')
Z=np.array(Z)
from sklearn import preprocessing  
#min_max_scaler = preprocessing.MinMaxScaler() 
#Z=Z_minMax = min_max_scaler.fit_transform(Z)
print(Z)
print(len(Z[0]))
print(len(Z))

[[ 1  0  0 ...  0  0  6]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  8]
 ...
 [ 0  0  0 ...  0  0  6]
 [ 0  0  0 ...  0  0 13]
 [ 0  0  0 ...  0  0  8]]
2662
200


In [16]:
Z_predict = clf.predict(Z)
print(Z_predict)

[0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1]


In [17]:
Z_predict = clf.predict(Z)
df=pd.DataFrame(Z_predict)
df.to_csv("2015-2024.新.csv",index=False,header=False)

In [18]:
Z_predict = clf.predict_proba(Z)
print(Z_predict)

[[5.07122416e-01 4.92877584e-01]
 [5.01118028e-01 4.98881972e-01]
 [5.59208200e-02 9.44079180e-01]
 [8.11465189e-03 9.91885348e-01]
 [5.47633645e-03 9.94523664e-01]
 [2.68806229e-02 9.73119377e-01]
 [3.54296765e-02 9.64570323e-01]
 [7.38152391e-02 9.26184761e-01]
 [5.95537739e-01 4.04462261e-01]
 [4.70206761e-02 9.52979324e-01]
 [5.36944240e-02 9.46305576e-01]
 [2.11016625e-02 9.78898337e-01]
 [1.17320061e-02 9.88267994e-01]
 [2.21451685e-03 9.97785483e-01]
 [1.83141598e-02 9.81685840e-01]
 [7.49122018e-03 9.92508780e-01]
 [6.61493825e-03 9.93385062e-01]
 [4.80667239e-02 9.51933276e-01]
 [2.25382851e-02 9.77461715e-01]
 [6.80662580e-02 9.31933742e-01]
 [1.48435658e-01 8.51564342e-01]
 [9.76200122e-01 2.37998776e-02]
 [2.60531653e-02 9.73946835e-01]
 [1.48526039e-02 9.85147396e-01]
 [1.39506689e-02 9.86049331e-01]
 [1.50302257e-02 9.84969774e-01]
 [4.87086634e-03 9.95129134e-01]
 [4.68870951e-02 9.53112905e-01]
 [1.21384066e-02 9.87861593e-01]
 [1.37201351e-02 9.86279865e-01]
 [2.305123

In [19]:
Z_predict = clf.predict_proba(Z)
df=pd.DataFrame(Z_predict)
df.to_csv("2015-2024.新0.csv",index=False,header=False)

In [14]:
#随机划分

In [15]:
from sklearn.model_selection import train_test_split
X_train,  X_test,  T_train,  T_test  =  train_test_split(X,T,test_size=0.1,random_state=90)

In [32]:
from sklearn.svm import SVC  # Support Vector Classifier
clf = SVC(kernel='linear') # 线性核函数
clf.fit(X_train,T_train)
SVC(C=1, cache_size=2000, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, cache_size=2000, gamma='auto_deprecated', kernel='linear')

In [15]:
import pandas as pd
import numpy as np
import time
import logging
import os, sys
import psutil
import lightgbm as lgb
from datetime import datetime

from itertools import cycle
from sklearn import svm
from sklearn.metrics import *

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
#from sklearn.externals import joblib
from scipy import interp

T_pred = clf.predict(X_test)
confusion_matrix(T_test, T_pred)

array([[106,   7],
       [ 28,  65]])

In [16]:
print (classification_report(T_test, T_pred , digits=4))

              precision    recall  f1-score   support

           0     0.7910    0.9381    0.8583       113
           1     0.9028    0.6989    0.7879        93

    accuracy                         0.8301       206
   macro avg     0.8469    0.8185    0.8231       206
weighted avg     0.8415    0.8301    0.8265       206



In [17]:
f1=f1_score(T_test,T_pred,average='micro')
print("the f1 score: %.3f"%f1)

the f1 score: 0.830


In [35]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='liblinear',multi_class='ovr', C = 10, verbose =10, max_iter=600)
clf.fit(X_train, T_train)

/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibLinear]iter  1 act 5.435e+03 pre 4.779e+03 delta 7.952e-01 f 1.280e+04 |g| 4.444e+04 CG   6
cg reaches trust region boundary
iter  2 act 1.777e+03 pre 1.474e+03 delta 1.119e+00 f 7.368e+03 |g| 1.480e+04 CG   6
cg reaches trust region boundary
iter  3 act 1.164e+03 pre 1.015e+03 delta 1.656e+00 f 5.591e+03 |g| 7.380e+03 CG   5
cg reaches trust region boundary
iter  4 act 9.738e+02 pre 8.715e+02 delta 2.205e+00 f 4.427e+03 |g| 3.586e+03 CG   7
cg reaches trust region boundary
iter  5 act 7.833e+02 pre 6.910e+02 delta 2.753e+00 f 3.454e+03 |g| 1.538e+03 CG   8
cg reaches trust region boundary
iter  6 act 6.475e+02 pre 5.680e+02 delta 3.447e+00 f 2.670e+03 |g| 1.214e+03 CG  10
cg reaches trust region boundary
iter  7 act 5.139e+02 pre 4.570e+02 delta 4.251e+00 f 2.023e+03 |g| 1.454e+03 CG  12
cg reaches trust region boundary
iter  8 act 4.108e+02 pre 3.463e+02 delta 5.354e+00 f 1.509e+03 |g| 7.598e+02 CG  15
cg reaches trust region boundary
iter  9 act 2.593e+02 pre 2.493e+02 delta 5.6

LogisticRegression(C=10, max_iter=600, multi_class='ovr', solver='liblinear',
                   verbose=10)

In [19]:
import pandas as pd
import numpy as np
import time
import logging
import os, sys
import psutil
import lightgbm as lgb
from datetime import datetime

from itertools import cycle
from sklearn import svm
from sklearn.metrics import *

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier

from scipy import interp

T_pred = clf.predict(X_test)
confusion_matrix(T_test, T_pred)

array([[88, 25],
       [16, 77]])

In [20]:
precision_score(T_test, T_pred,average='micro')
recall_score(T_test, T_pred,average='micro')
f1_score(T_test, T_pred,average='micro')

0.8009708737864077

In [21]:
print (classification_report(T_test, T_pred , digits=4))

              precision    recall  f1-score   support

           0     0.8462    0.7788    0.8111       113
           1     0.7549    0.8280    0.7897        93

    accuracy                         0.8010       206
   macro avg     0.8005    0.8034    0.8004       206
weighted avg     0.8050    0.8010    0.8014       206



In [18]:
T_pred = clf.predict(X_train)
confusion_matrix(T_train, T_pred)

array([[953,   1],
       [  1, 892]])

In [19]:
print (classification_report(T_train, T_pred , digits=4))

              precision    recall  f1-score   support

           0     0.9990    0.9990    0.9990       954
           1     0.9989    0.9989    0.9989       893

    accuracy                         0.9989      1847
   macro avg     0.9989    0.9989    0.9989      1847
weighted avg     0.9989    0.9989    0.9989      1847



In [25]:
y_pred_test=clf.predict(X_test)
df=pd.DataFrame(y_pred_test)
df.to_csv("./resulttestPLQYPreFENLEI.csv",index=False,header=False)
y_true=T_test
df=pd.DataFrame(y_true)
df.to_csv("./resulttestPLQYTrueFENLEI.csv",index=False,header=False)

In [14]:
import sklearn.neural_network as sk_nn
clf = sk_nn.MLPClassifier(activation='relu',solver='adam',alpha=0.1,learning_rate='adaptive',learning_rate_init=0.1,max_iter=800)
clf.fit(X_train,T_train)


/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(alpha=0.1, learning_rate='adaptive', learning_rate_init=0.1,
              max_iter=800)

In [21]:
T_pred = clf.predict(X_train)
confusion_matrix(T_train, T_pred)

array([[884,  70],
       [ 94, 799]])

In [22]:
T_pred = clf.predict(X_test)
confusion_matrix(T_test, T_pred)

array([[99, 14],
       [21, 72]])

In [23]:
print (classification_report(T_test, T_pred , digits=4))

              precision    recall  f1-score   support

           0     0.8250    0.8761    0.8498       113
           1     0.8372    0.7742    0.8045        93

    accuracy                         0.8301       206
   macro avg     0.8311    0.8251    0.8271       206
weighted avg     0.8305    0.8301    0.8293       206



In [14]:
import sklearn.neighbors as sk_neighbors
clf = sk_neighbors.KNeighborsClassifier(n_neighbors=3) 
clf.fit(X_train,T_train)

/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [237]:
3 (28)

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_79497/2799706359.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  3 (28)


TypeError: 'int' object is not callable

In [16]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier (
bootstrap=True, max_depth=None,
max_features='auto', max_leaf_nodes=None,
min_impurity_decrease=0.0,
min_samples_leaf=1, min_samples_split=10,
min_weight_fraction_leaf=0.0, n_estimators=600, n_jobs=2,
oob_score=False, random_state=725, verbose=0, warm_start=False)
clf.fit(X_train,T_train) # 使用训练集训练模型
T_pre = clf.predict(X_test) # 使用模型对测试集进行预测

/tmp/ipykernel_36868/1181146878.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train,T_train) # 使用训练集训练模型


In [34]:
from sklearn.tree import DecisionTreeClassifier
 
clf = DecisionTreeClassifier(
    splitter="best",
    max_depth=None,
    min_samples_split=50,
    min_samples_leaf=10,
    min_weight_fraction_leaf=0.0,
    max_features=0.6,
    random_state=2,
    max_leaf_nodes=None,
    min_impurity_decrease=0)
 # 所以参数均置为默认状态
clf.fit(X_train,T_train) # 使用训练集训练模型
T_pre = clf.predict(X_test) # 使用模型对测试集进行预测

In [35]:
from sklearn.metrics import accuracy_score
 
print (accuracy_score(T_pre, T_test))

0.8009708737864077


In [36]:
T_pred = clf.predict(X_test)
confusion_matrix(T_test, T_pred)

array([[97, 16],
       [25, 68]])

In [37]:
print (classification_report(T_test, T_pred , digits=4))

              precision    recall  f1-score   support

           0     0.7951    0.8584    0.8255       113
           1     0.8095    0.7312    0.7684        93

    accuracy                         0.8010       206
   macro avg     0.8023    0.7948    0.7969       206
weighted avg     0.8016    0.8010    0.7997       206



In [54]:
clf = svm.SVC(kernel='linear')
clf.fit(X_train,T_train)

/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [55]:
from sklearn.svm import SVC  # Support Vector Classifier
clf = SVC(kernel='linear') # 线性核函数
clf.fit(X_train,T_train)
SVC(C=10.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

/home/rdkit/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10.0, gamma='auto_deprecated', kernel='linear')